
FROM python:3.9


WORKDIR /code


COPY ./requirements.txt /code/requirements.txt


RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


COPY ./lib /code/lib
COPY ./main.py /code/main.py

EXPOSE 8001


CMD ["fastapi", "run", "/code/main.py", "--port", "8001"]